baseURL = "https://iambyexample.org/"
languageCode = "en-us"
title = "IAM By Example"
theme = "digitalgarden"

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']

[menu]
[[menu.main]]
  name = 'AWS'
  url = '/aws'
  weight = 1

[[menu.main]]
  name = 'Google Cloud'
  url = '/gcp'
  weight = 2

[[menu.main]]
  name = 'Azure'
  url = '/azure'
  weight = 3

[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com'
  weight = 2

[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 9


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true